-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPRESA` (
  `idEMPRESA` INT NOT NULL AUTO_INCREMENT,
  `NOMEFANTASIA` VARCHAR(45) NOT NULL,
  `RAZAOSOCIAL` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `TELEFONE` VARCHAR(45) NOT NULL,
  `FOTO` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEMPRESA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `idUSUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DATANASCIMENTO` VARCHAR(45) NOT NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `TELEFONE` VARCHAR(45) NOT NULL,
  `FOTO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUSUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA` (
  `idCATEGORIA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCATEGORIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPOPRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPOPRODUTO` (
  `idTIPOPRODUTO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTIPOPRODUTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTO` (
  `idPRODUTO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(45) NOT NULL,
  `VALOR` VARCHAR(45) NOT NULL,
  `IDEMPRESA` INT NOT NULL,
  `IDTIPOPRODUTO` INT NOT NULL,
  `FOTO` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idPRODUTO`),
  INDEX `fk_PRODUTO_EMPRESA1_idx` (`IDEMPRESA` ASC) VISIBLE,
  INDEX `fk_PRODUTO_TIPOPRODUTO1_idx` (`IDTIPOPRODUTO` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTO_EMPRESA1`
    FOREIGN KEY (`IDEMPRESA`)
    REFERENCES `mydb`.`EMPRESA` (`idEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_TIPOPRODUTO1`
    FOREIGN KEY (`IDTIPOPRODUTO`)
    REFERENCES `mydb`.`TIPOPRODUTO` (`idTIPOPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BIBLIOTECA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BIBLIOTECA` (
  `USUARIO_idUSUARIO` INT NOT NULL,
  `PRODUTO_idPRODUTO` INT NOT NULL,
  `DATA` DATETIME NOT NULL,
  PRIMARY KEY (`USUARIO_idUSUARIO`, `PRODUTO_idPRODUTO`),
  INDEX `fk_USUARIO_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_idPRODUTO` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_PRODUTO_USUARIO_idx` (`USUARIO_idUSUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_PRODUTO_USUARIO`
    FOREIGN KEY (`USUARIO_idUSUARIO`)
    REFERENCES `mydb`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPRODUTO`)
    REFERENCES `mydb`.`PRODUTO` (`idPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA_PRODUTO` (
  `IDCATEGORIA` INT NOT NULL,
  `IDPRODUTO` INT NOT NULL,
  PRIMARY KEY (`IDCATEGORIA`, `IDPRODUTO`),
  INDEX `fk_CATEGORIA_has_PRODUTO_PRODUTO1_idx` (`IDPRODUTO` ASC) VISIBLE,
  INDEX `fk_CATEGORIA_has_PRODUTO_CATEGORIA1_idx` (`IDCATEGORIA` ASC) VISIBLE,
  CONSTRAINT `fk_CATEGORIA_has_PRODUTO_CATEGORIA1`
    FOREIGN KEY (`IDCATEGORIA`)
    REFERENCES `mydb`.`CATEGORIA` (`idCATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CATEGORIA_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`IDPRODUTO`)
    REFERENCES `mydb`.`PRODUTO` (`idPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRANSACAO_CARTEIRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRANSACAO_CARTEIRA` (
  `idTRANSACAO_CARTEIRA` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_idUSUARIO` INT NOT NULL,
  `SALDO` VARCHAR(45) NOT NULL,
  `DATAPAGAMENTO` DATETIME NOT NULL,
  `PRODUTO_idPRODUTO` INT NOT NULL,
  PRIMARY KEY (`idTRANSACAO_CARTEIRA`),
  INDEX `fk_TRANSACAO_CARTEIRA_USUARIO1_idx` (`USUARIO_idUSUARIO` ASC) VISIBLE,
  INDEX `fk_TRANSACAO_CARTEIRA_PRODUTO1_idx` (`PRODUTO_idPRODUTO` ASC) VISIBLE,
  CONSTRAINT `fk_TRANSACAO_CARTEIRA_USUARIO1`
    FOREIGN KEY (`USUARIO_idUSUARIO`)
    REFERENCES `mydb`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACAO_CARTEIRA_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPRODUTO`)
    REFERENCES `mydb`.`PRODUTO` (`idPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CARRINHO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CARRINHO` (
  `idCARRINHO` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_idUSUARIO` INT NOT NULL,
  `PRODUTO_idPRODUTO` INT NOT NULL,
  `DATA` DATETIME NOT NULL,
  PRIMARY KEY (`idCARRINHO`),
  INDEX `fk_CARRINHO_USUARIO1_idx` (`USUARIO_idUSUARIO` ASC) VISIBLE,
  INDEX `fk_CARRINHO_PRODUTO1_idx` (`PRODUTO_idPRODUTO` ASC) VISIBLE,
  CONSTRAINT `fk_CARRINHO_USUARIO1`
    FOREIGN KEY (`USUARIO_idUSUARIO`)
    REFERENCES `mydb`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARRINHO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPRODUTO`)
    REFERENCES `mydb`.`PRODUTO` (`idPRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
